/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.datapool.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
/**
 * CacheMetadataKey
 */
public class CacheMetadataKey {
  public static final String SERIALIZED_NAME_CACHE_NAME = "cacheName";
  @SerializedName(SERIALIZED_NAME_CACHE_NAME)
  private String cacheName;

  public static final String SERIALIZED_NAME_PROJECT = "project";
  @SerializedName(SERIALIZED_NAME_PROJECT)
  private String project;

  public static final String SERIALIZED_NAME_PUBLIC_CACHE_NAME = "publicCacheName";
  @SerializedName(SERIALIZED_NAME_PUBLIC_CACHE_NAME)
  private String publicCacheName;


  public CacheMetadataKey cacheName(String cacheName) {
    
    this.cacheName = cacheName;
    return this;
  }

   /**
   * Get cacheName
   * @return cacheName
  **/


  public String getCacheName() {
    return cacheName;
  }


  public void setCacheName(String cacheName) {
    this.cacheName = cacheName;
  }


  public CacheMetadataKey project(String project) {
    
    this.project = project;
    return this;
  }

   /**
   * Get project
   * @return project
  **/


  public String getProject() {
    return project;
  }


  public void setProject(String project) {
    this.project = project;
  }


  public CacheMetadataKey publicCacheName(String publicCacheName) {
    
    this.publicCacheName = publicCacheName;
    return this;
  }

   /**
   * Get publicCacheName
   * @return publicCacheName
  **/


  public String getPublicCacheName() {
    return publicCacheName;
  }


  public void setPublicCacheName(String publicCacheName) {
    this.publicCacheName = publicCacheName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CacheMetadataKey cacheMetadataKey = (CacheMetadataKey) o;
    return Objects.equals(this.cacheName, cacheMetadataKey.cacheName) &&
        Objects.equals(this.project, cacheMetadataKey.project) &&
        Objects.equals(this.publicCacheName, cacheMetadataKey.publicCacheName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cacheName, project, publicCacheName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CacheMetadataKey {\n");
    sb.append("    cacheName: ").append(toIndentedString(cacheName)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    publicCacheName: ").append(toIndentedString(publicCacheName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

