/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.datapool.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.datapool.model.PostgresJdbcProps;

/**
 * CreateJdbcCacheRequest
 */
public class CreateJdbcCacheRequest {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_PROJECT_ID = "projectId";
  @SerializedName(SERIALIZED_NAME_PROJECT_ID)
  private String projectId;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_CACHE_NAME = "cacheName";
  @SerializedName(SERIALIZED_NAME_CACHE_NAME)
  private String cacheName;

  public static final String SERIALIZED_NAME_PROPERTIES = "properties";
  @SerializedName(SERIALIZED_NAME_PROPERTIES)
  private PostgresJdbcProps properties;

  public static final String SERIALIZED_NAME_QUERY = "query";
  @SerializedName(SERIALIZED_NAME_QUERY)
  private String query;


  public CreateJdbcCacheRequest id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/


  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public CreateJdbcCacheRequest projectId(String projectId) {
    
    this.projectId = projectId;
    return this;
  }

   /**
   * Get projectId
   * @return projectId
  **/


  public String getProjectId() {
    return projectId;
  }


  public void setProjectId(String projectId) {
    this.projectId = projectId;
  }


  public CreateJdbcCacheRequest name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/


  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public CreateJdbcCacheRequest cacheName(String cacheName) {
    
    this.cacheName = cacheName;
    return this;
  }

   /**
   * Get cacheName
   * @return cacheName
  **/


  public String getCacheName() {
    return cacheName;
  }


  public void setCacheName(String cacheName) {
    this.cacheName = cacheName;
  }


  public CreateJdbcCacheRequest properties(PostgresJdbcProps properties) {
    
    this.properties = properties;
    return this;
  }

   /**
   * Get properties
   * @return properties
  **/


  public PostgresJdbcProps getProperties() {
    return properties;
  }


  public void setProperties(PostgresJdbcProps properties) {
    this.properties = properties;
  }


  public CreateJdbcCacheRequest query(String query) {
    
    this.query = query;
    return this;
  }

   /**
   * Get query
   * @return query
  **/


  public String getQuery() {
    return query;
  }


  public void setQuery(String query) {
    this.query = query;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateJdbcCacheRequest createJdbcCacheRequest = (CreateJdbcCacheRequest) o;
    return Objects.equals(this.id, createJdbcCacheRequest.id) &&
        Objects.equals(this.projectId, createJdbcCacheRequest.projectId) &&
        Objects.equals(this.name, createJdbcCacheRequest.name) &&
        Objects.equals(this.cacheName, createJdbcCacheRequest.cacheName) &&
        Objects.equals(this.properties, createJdbcCacheRequest.properties) &&
        Objects.equals(this.query, createJdbcCacheRequest.query);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, projectId, name, cacheName, properties, query);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateJdbcCacheRequest {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    cacheName: ").append(toIndentedString(cacheName)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

