/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.datapool.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.datapool.model.CacheMetadata;

/**
 * InternalApiRequestCacheMetadata
 */
public class InternalApiRequestCacheMetadata {
  public static final String SERIALIZED_NAME_RESULT = "result";
  @SerializedName(SERIALIZED_NAME_RESULT)
  private CacheMetadata result;

  public static final String SERIALIZED_NAME_SUCCESS = "success";
  @SerializedName(SERIALIZED_NAME_SUCCESS)
  private Boolean success;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;


  public InternalApiRequestCacheMetadata result(CacheMetadata result) {
    
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/


  public CacheMetadata getResult() {
    return result;
  }


  public void setResult(CacheMetadata result) {
    this.result = result;
  }


  public InternalApiRequestCacheMetadata success(Boolean success) {
    
    this.success = success;
    return this;
  }

   /**
   * Get success
   * @return success
  **/


  public Boolean getSuccess() {
    return success;
  }


  public void setSuccess(Boolean success) {
    this.success = success;
  }


  public InternalApiRequestCacheMetadata message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/


  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InternalApiRequestCacheMetadata internalApiRequestCacheMetadata = (InternalApiRequestCacheMetadata) o;
    return Objects.equals(this.result, internalApiRequestCacheMetadata.result) &&
        Objects.equals(this.success, internalApiRequestCacheMetadata.success) &&
        Objects.equals(this.message, internalApiRequestCacheMetadata.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(result, success, message);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InternalApiRequestCacheMetadata {\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

